// <auto-generated />
using System;
using ApiTier7Provision.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiTier7Provision.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509115544_RemoveBandwidthCostFromInstances")]
    partial class RemoveBandwidthCostFromInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiTier7Provision.Domain.Entities.HealthCheckLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoggedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at_utc");

                    b.HasKey("Id");

                    b.ToTable("health_check_logs", (string)null);
                });

            modelBuilder.Entity("ApiTier7Provision.Domain.Entities.ModelTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("ProvisioningTemplateUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provisioning_template_uuid");

                    b.PrimitiveCollection<string[]>("SupportedGpus")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("supported_gpus");

                    b.HasKey("Id");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.ToTable("model_templates", (string)null);
                });

            modelBuilder.Entity("ApiTier7Provision.Domain.Entities.ProvisionedInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EgressCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("egress_cost");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gpu");

                    b.Property<decimal>("IngressCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("ingress_cost");

                    b.Property<int>("ModelTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("model_template_id");

                    b.Property<DateTime>("ProvisionedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provisioned_at_utc");

                    b.Property<decimal>("TotalCostPerHour")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("total_cost_per_hour");

                    b.Property<long>("VastInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("vast_instance_id");

                    b.HasKey("Id");

                    b.HasIndex("ModelTemplateId");

                    b.HasIndex("VastInstanceId")
                        .IsUnique();

                    b.ToTable("instances", (string)null);
                });

            modelBuilder.Entity("ApiTier7Provision.Domain.Entities.ProvisionedInstance", b =>
                {
                    b.HasOne("ApiTier7Provision.Domain.Entities.ModelTemplate", "ModelTemplate")
                        .WithMany("Instances")
                        .HasForeignKey("ModelTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelTemplate");
                });

            modelBuilder.Entity("ApiTier7Provision.Domain.Entities.ModelTemplate", b =>
                {
                    b.Navigation("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
