@ApiTier7Provision.Api_HostAddress = http://localhost:5019

GET {{ApiTier7Provision.Api_HostAddress}}/api/health
Accept: application/json

###

GET {{ApiTier7Provision.Api_HostAddress}}/api/templates?model=llama-3
Accept: application/json

###

DELETE {{ApiTier7Provision.Api_HostAddress}}/api/templates?model=llama-3
Accept: application/json

###

GET {{ApiTier7Provision.Api_HostAddress}}/api/instances?limit=5
Accept: application/json

###

POST {{ApiTier7Provision.Api_HostAddress}}/api/instances/offers
Content-Type: application/json
Accept: application/json

{
  "limit": 100,
  "type": "ondemand",
  "verified": { "eq": true },
  "rentable": { "eq": true },
  "rented": { "eq": false },
  "num_gpus": { "gte": 4 },
  "reliability": { "gt": 0.99 },
  "order": [
    ["dph_total", "asc"]
  ]
}

###

PUT {{ApiTier7Provision.Api_HostAddress}}/api/instances/asks/1234567
Content-Type: application/json
Accept: application/json

{
  "image": "vastai/base-image:@vastai-automatic-tag",
  "label": "example-instance",
  "disk": 20,
  "runtype": "ssh"
}

###

PUT {{ApiTier7Provision.Api_HostAddress}}/api/instances/1234567
Content-Type: application/json
Accept: application/json

{
  "state": "stopped",
  "label": "My ML Training Job"
}

###

DELETE {{ApiTier7Provision.Api_HostAddress}}/api/instances/1234567
Accept: application/json

###

PUT {{ApiTier7Provision.Api_HostAddress}}/api/instances/reboot/1234567
Accept: application/json

###
